CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210920193721_InitialCreate') THEN
    CREATE TABLE "Accounts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Username" character varying(12) NOT NULL,
        "Attack_CurrentLevel" integer NULL,
        "Attack_BaseLevel" integer NULL,
        "Defense_CurrentLevel" integer NULL,
        "Defense_BaseLevel" integer NULL,
        "Strength_CurrentLevel" integer NULL,
        "Strength_BaseLevel" integer NULL,
        "Hits_CurrentLevel" integer NULL,
        "Hits_BaseLevel" integer NULL,
        "Ranged_CurrentLevel" integer NULL,
        "Ranged_BaseLevel" integer NULL,
        "Prayer_CurrentLevel" integer NULL,
        "Prayer_BaseLevel" integer NULL,
        "Magic_CurrentLevel" integer NULL,
        "Magic_BaseLevel" integer NULL,
        "Cooking_CurrentLevel" integer NULL,
        "Cooking_BaseLevel" integer NULL,
        "Woodcut_CurrentLevel" integer NULL,
        "Woodcut_BaseLevel" integer NULL,
        "Fletching_CurrentLevel" integer NULL,
        "Fletching_BaseLevel" integer NULL,
        "Fishing_CurrentLevel" integer NULL,
        "Fishing_BaseLevel" integer NULL,
        "Firemaking_CurrentLevel" integer NULL,
        "Firemaking_BaseLevel" integer NULL,
        "Crafting_CurrentLevel" integer NULL,
        "Crafting_BaseLevel" integer NULL,
        "Smithing_CurrentLevel" integer NULL,
        "Smithing_BaseLevel" integer NULL,
        "Mining_CurrentLevel" integer NULL,
        "Mining_BaseLevel" integer NULL,
        "Herblaw_CurrentLevel" integer NULL,
        "Herblaw_BaseLevel" integer NULL,
        "Agility_CurrentLevel" integer NULL,
        "Agility_BaseLevel" integer NULL,
        "Thieving_CurrentLevel" integer NULL,
        "Thieving_BaseLevel" integer NULL,
        CONSTRAINT "PK_Accounts" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210920193721_InitialCreate') THEN
    CREATE TABLE "ItemDefinitions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ItemId" integer NOT NULL,
        "Name" integer NOT NULL,
        "IsStackable" boolean NOT NULL,
        CONSTRAINT "PK_ItemDefinitions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210920193721_InitialCreate') THEN
    CREATE TABLE "BankItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Count" integer NOT NULL,
        "DefinitionId" integer NOT NULL,
        "AccountId" integer NOT NULL,
        CONSTRAINT "PK_BankItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_BankItems_Accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES "Accounts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_BankItems_ItemDefinitions_DefinitionId" FOREIGN KEY ("DefinitionId") REFERENCES "ItemDefinitions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210920193721_InitialCreate') THEN
    CREATE TABLE "InventoryItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Count" integer NOT NULL,
        "DefinitionId" integer NOT NULL,
        "AccountId" integer NOT NULL,
        CONSTRAINT "PK_InventoryItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_InventoryItems_Accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES "Accounts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_InventoryItems_ItemDefinitions_DefinitionId" FOREIGN KEY ("DefinitionId") REFERENCES "ItemDefinitions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210920193721_InitialCreate') THEN
    CREATE INDEX "IX_BankItems_AccountId" ON "BankItems" ("AccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210920193721_InitialCreate') THEN
    CREATE INDEX "IX_BankItems_DefinitionId" ON "BankItems" ("DefinitionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210920193721_InitialCreate') THEN
    CREATE INDEX "IX_InventoryItems_AccountId" ON "InventoryItems" ("AccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210920193721_InitialCreate') THEN
    CREATE INDEX "IX_InventoryItems_DefinitionId" ON "InventoryItems" ("DefinitionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210920193721_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210920193721_InitialCreate', '5.0.10');
    END IF;
END $EF$;
COMMIT;

